### ISSUE TITLE
방명록

### ISSUE THREAD

**Issue by hye5nee123** [qpqp12121/java_master#1]
__ ㆀ● ''
__ ┏■┛ 후다다닥....
____┛┓

..Oooo　
　(　 )　 도장을....
　 ). /　
　(_/　
..Oooo　
　(　 )　 발도장을....
　 ). /　
　(_/　
..Oooo　
　(　 )　 꾹꾹꾸~~욱
　 ). /　
　(_/　
..Oooo　
　(　 )　
　 ). /　 찍고 돌아가......
　(_/　

.''●ㆀ -----
.┗■┓------ 휘리리릭~~~
-┏┗-------

**Comment by eonn0** [comment]
zㅋㅋㅋㅋ연상녀라 그런가 행동이 느리십니다 앞으로는 빨리 빨리 움직이도록!!

**Comment by hye5nee123** [comment]
![image](https://github.com/qpqp12121/java_master/assets/152113818/e422ed2b-f27e-4ca3-aeb0-141d379d5378)
